export const OPEN_ACCOUNT = "OPEN_ACCOUNT";
export const CREATE_USER = "CREATE_USER";
export const CHANGE_ACC_STATUS = "CHANGE_ACC_STATUS";
export const MAKE_TRANSACTION = "MAKE_TRANSACTION";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";